# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_raojixian(object):
    def setupUi(self, raojixian):
        raojixian.setObjectName("raojixian")
        raojixian.resize(1087, 823)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/cdc.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        raojixian.setWindowIcon(icon)
        raojixian.setWindowTitle("东部战区疾病预防控制中心")
        self.centralwidget = QtWidgets.QWidget(raojixian)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.widget = QtWidgets.QWidget(self.login)
        self.widget.setGeometry(QtCore.QRect(390, 330, 301, 201))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.login, "")
        self.luru = QtWidgets.QWidget()
        self.luru.setObjectName("luru")
        self.gridLayoutWidget = QtWidgets.QWidget(self.luru)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1061, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 6, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 2, 5, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_4.addWidget(self.lineEdit_14, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_4.addWidget(self.lineEdit_13, 2, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 0, 5, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 2, 7, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 6, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 0, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 0, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 2, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_4.addWidget(self.lineEdit_33, 3, 7, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_4.addWidget(self.lineEdit_15, 3, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_4.addWidget(self.lineEdit_16, 3, 5, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_4.addWidget(self.lineEdit_12, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 0, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_4.addWidget(self.lineEdit_34, 4, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.luru)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 370, 581, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.luru)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(610, 370, 451, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.luru)
        self.lineEdit_8.setGeometry(QtCore.QRect(375, 806, 39, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.tabWidget.addTab(self.luru, "")
        self.jingfei = QtWidgets.QWidget()
        self.jingfei.setObjectName("jingfei")
        self.tableWidget = QtWidgets.QTableWidget(self.jingfei)
        self.tableWidget.setGeometry(QtCore.QRect(80, 170, 981, 361))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.listWidget = QtWidgets.QListWidget(self.jingfei)
        self.listWidget.setGeometry(QtCore.QRect(0, 170, 81, 361))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tabWidget.addTab(self.jingfei, "")
        self.xianshi = QtWidgets.QWidget()
        self.xianshi.setObjectName("xianshi")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.xianshi)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 80, 1051, 721))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.widget1 = QtWidgets.QWidget(self.xianshi)
        self.widget1.setGeometry(QtCore.QRect(0, 30, 1041, 32))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_6.addWidget(self.lineEdit_35)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.tabWidget.addTab(self.xianshi, "")
        self.renwushu = QtWidgets.QWidget()
        self.renwushu.setObjectName("renwushu")
        self.textEdit_3 = QtWidgets.QTextEdit(self.renwushu)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 0, 1051, 791))
        self.textEdit_3.setObjectName("textEdit_3")
        self.tabWidget.addTab(self.renwushu, "")
        self.caiwu = QtWidgets.QWidget()
        self.caiwu.setObjectName("caiwu")
        self.textEdit_4 = QtWidgets.QTextEdit(self.caiwu)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 0, 1061, 801))
        self.textEdit_4.setObjectName("textEdit_4")
        self.tabWidget.addTab(self.caiwu, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        raojixian.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(raojixian)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        raojixian.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(raojixian)
        self.toolBar.setObjectName("toolBar")
        raojixian.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiondakai = QtWidgets.QAction(raojixian)
        self.actiondakai.setObjectName("actiondakai")
        self.actionedit = QtWidgets.QAction(raojixian)
        self.actionedit.setObjectName("actionedit")
        self.actiondakai_2 = QtWidgets.QAction(raojixian)
        self.actiondakai_2.setObjectName("actiondakai_2")
        self.actionbaocun = QtWidgets.QAction(raojixian)
        self.actionbaocun.setObjectName("actionbaocun")
        self.actionshezhi = QtWidgets.QAction(raojixian)
        self.actionshezhi.setObjectName("actionshezhi")
        self.menu.addAction(self.actiondakai)
        self.menu.addAction(self.actiondakai_2)
        self.menu.addAction(self.actionbaocun)
        self.menu_2.addAction(self.actionedit)
        self.menu_2.addAction(self.actionshezhi)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(raojixian)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(raojixian)

    def retranslateUi(self, raojixian):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("raojixian", "账号"))
        self.label_3.setText(_translate("raojixian", "密码"))
        self.pushButton.setText(_translate("raojixian", "登录"))
        self.pushButton_2.setText(_translate("raojixian", "注册"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login), _translate("raojixian", "登录"))
        self.label_5.setText(_translate("raojixian", "所科"))
        self.label_6.setText(_translate("raojixian", "职称"))
        self.label_7.setText(_translate("raojixian", "课题编号"))
        self.label_11.setText(_translate("raojixian", "课题名称"))
        self.label_12.setText(_translate("raojixian", "课题经费"))
        self.label_9.setText(_translate("raojixian", "负责人"))
        self.label_4.setText(_translate("raojixian", "证件号"))
        self.label_10.setText(_translate("raojixian", "电话"))
        self.label_14.setText(_translate("raojixian", "结题验收"))
        self.label_15.setText(_translate("raojixian", "成果转化"))
        self.label_8.setText(_translate("raojixian", "出生年月"))
        self.label_13.setText(_translate("raojixian", "中期检查"))
        self.label_16.setText(_translate("raojixian", "课题时间"))
        self.label_17.setText(_translate("raojixian", "内容简介"))
        self.pushButton_9.setText(_translate("raojixian", "上传科研成果"))
        self.pushButton_5.setText(_translate("raojixian", "上传科研任务书"))
        self.pushButton_6.setText(_translate("raojixian", "确认"))
        self.pushButton_7.setText(_translate("raojixian", "取消"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.luru), _translate("raojixian", "录入"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("raojixian", "直接经费"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("raojixian", "设备费"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("raojixian", "材料费"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("raojixian", "测试化验加工费"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("raojixian", "差旅费"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("raojixian", "会议费"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("raojixian", "出版/文献/信息传播/知识产权事务费"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("raojixian", "劳务费"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("raojixian", "专家咨询费"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("raojixian", "其他费用"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("raojixian", "间接经费"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("raojixian", "批准数"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("raojixian", "已开销"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("raojixian", "结余"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("raojixian", "经费申请数"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("raojixian", "第一年度"))
        item = self.listWidget.item(1)
        item.setText(_translate("raojixian", "第二年度"))
        item = self.listWidget.item(2)
        item.setText(_translate("raojixian", "第三年度"))
        item = self.listWidget.item(3)
        item.setText(_translate("raojixian", "第四年度"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jingfei), _translate("raojixian", "课题经费"))
        self.pushButton_8.setText(_translate("raojixian", "搜索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xianshi), _translate("raojixian", "检索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.renwushu), _translate("raojixian", "科研任务书"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.caiwu), _translate("raojixian", "成果"))
        self.menu.setTitle(_translate("raojixian", "文件"))
        self.menu_2.setTitle(_translate("raojixian", "编辑"))
        self.menu_3.setTitle(_translate("raojixian", "视图"))
        self.menu_4.setTitle(_translate("raojixian", "帮助"))
        self.toolBar.setWindowTitle(_translate("raojixian", "toolBar"))
        self.actiondakai.setText(_translate("raojixian", "新建"))
        self.actionedit.setText(_translate("raojixian", "编辑"))
        self.actiondakai_2.setText(_translate("raojixian", "打开"))
        self.actionbaocun.setText(_translate("raojixian", "保存"))
        self.actionshezhi.setText(_translate("raojixian", "设置"))

