# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Caohanshu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(979, 575)
        Form.setWindowTitle('饶继先的程序')
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(180, 150, 75, 23))
        self.btn1.setObjectName("btn1")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(290, 150, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(119, 210, 251, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.LabelRole, self.formLayout_2)
        self.btn2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn2.setObjectName("btn2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn3.setObjectName("btn3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btn3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(500, 230, 119, 96))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 91, 62))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 330, 206, 78))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(10, 30, 186, 18))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.isChecked()
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.btn4 = QtWidgets.QPushButton(Form)
        self.btn4.setGeometry(QtCore.QRect(390, 240, 75, 23))
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(Form)
        self.btn5.setGeometry(QtCore.QRect(390, 310, 75, 23))
        self.btn5.setObjectName("btn5")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(530, 420, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton.setGeometry(QtCore.QRect(440, 470, 185, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(710, 90, 113, 146))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(20, 20, 73, 106))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(490, 110, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = QtWidgets.QSlider(Form)
        self.verticalSlider.setGeometry(QtCore.QRect(800, 250, 22, 160))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(530, 170, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(Form)
        self.btn1.clicked.connect(self.btn1_click)
        self.btn2.clicked.connect(self.btn2_click)
        self.btn3.clicked.connect(self.btn3_click)
        self.btn4.clicked.connect(self.btn4_click)
        self.btn5.clicked.connect(self.btn5_click)
        self.buttonBox.accepted.connect(self.commandLinkButton.click)
        self.radioButton.clicked.connect(self.radioButton_click)
        self.radioButton_2.clicked.connect(self.radioButton_2_click)
        self.radioButton_3.clicked.connect(self.radioButton_3_click)
        self.radioButton_4.clicked.connect(self.radioButton_4_click)
        self.radioButton_5.clicked.connect(self.radioButton_5_click)
        # self.lcdNumber.valueChanged['int'].connect(self.lcdNumber_click)
        self.horizontalSlider.valueChanged['int'].connect(self.horizontalSlider_click)
        self.verticalSlider.valueChanged['int'].connect(self.verticalSlider_click)
        QtCore.QMetaObject.connectSlotsByName(self)

        # may_str = self.lineEdit_2.text()
        # print(self.textEdit.toPlainText())



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn1.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.btn2.setText(_translate("Form", "PushButton"))
        self.btn3.setText(_translate("Form", "PushButton"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.radioButton.setText(_translate("Form", "同意"))
        self.radioButton_2.setText(_translate("Form", "不同意"))
        self.radioButton_3.setText(_translate("Form", "不知道"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))
        self.radioButton_4.setText(_translate("Form", "确认"))
        self.radioButton_5.setText(_translate("Form", "取消"))
        self.btn4.setText(_translate("Form", "PushButton"))
        self.btn5.setText(_translate("Form", "PushButton"))
        self.commandLinkButton.setText(_translate("Form", "下一页"))
        self.groupBox_3.setTitle(_translate("Form", "GroupBox"))
        self.checkBox.setText(_translate("Form", "A"))
        self.checkBox_5.setText(_translate("Form", "B"))
        self.checkBox_4.setText(_translate("Form", "C"))
        self.checkBox_3.setText(_translate("Form", "D"))
        self.checkBox_2.setText(_translate("Form", "E"))

